# -*- coding: utf-8 -*-
"""Array Element Product.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10zsMnIpjg9rm-gbL5njADXCL1gL-Flqb
"""

def productOfElementsInArray(nums: list)-> list:
  return list(map(lambda x: x**2, nums))