# -*- coding: utf-8 -*-
"""Two SUm Unsorted Brute Force.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1izYbrRcgLFrEewiMowHgIyNCYwWxA9bd
"""

def bruteForceTwoSum(nums: list, target: int) -> list:

  for i in range(len(nums)):
    for j in range(len(nums)):
      if nums[i] != nums[j] and nums[i] + nums[j] == target:
        return [nums[i], nums[j]]

  else:
    return []