# -*- coding: utf-8 -*-
"""twoSum.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l1IPC2Tm5i5ctj7XkbkHOpj8piTiNQh3
"""

def twoSum(nums: list, target: int) -> list:

  complementMap = dict()

  for idx, value in enumerate(nums):
    complement = target - value

    if value in complementMap:
      return [complementMap[value], value]
    
    else:
      complementMap[complement] = value

  # In case no pairs add up to target
  else:
    return []